services:
  endlessh:
    image: shizunge/endlessh-go:latest
    container_name: endlessh
    restart: unless-stopped
    command:
      - -interval_ms=1000
      - -logtostderr
      - -v=1
    ports:
      - 22:2222

  fail2ban:
    image: lscr.io/linuxserver/fail2ban:1.0.2
    container_name: fail2ban
    restart: unless-stopped
    volumes:
      - ./jail.conf:/config/fail2ban/jain.conf
      - /var/log:/var/log:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host

