networks:
  ssl_pass:
    external: true

volumes:
  data:

services:
  password:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - data:/data/
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    networks:
      - ssl_pass


