networks:
  gitea:
  ssl_git:
    external: true

volumes:
  gitea_db:
  gitea_data:

services:
  gitea_server:
    image: gitea/gitea:1.21
    container_name: gitea_server
    restart: always
    volumes:
      - gitea_data:/data
      - ./theme.css:$GITEA_CUSTOM/public/assets/css
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: ${DB_TYPE}
      GITEA__database__HOST: gitea_db:3306
      GITEA__database__NAME: ${SQL_DB}
      GITEA__database__USER: ${SQL_USER}
      GITEA__database__PASSWD: ${SQL_PASSWORD}
      GITEA__service__DISABLE_REGISTRATION: ${DISABLE_REGISTRATION}
      GITEA__service__REQUIRE_SIGNIN_VIEW: ${DISABLE_REGISTRATION}
      GITEA__mailer__ENABLED: true
      GITEA__mailer__FROM: ${MAILER_FROM}
      GITEA__mailer__PROTOCOL: starttls
      GITEA__mailer__SMTP_ADDR: ${MAIL_SERVER}
      GITEA__mailer__SMTP_PORT: 587
      GITEA__mailer__USER: ${MAIL_USER}
      GITEA__mailer__PASSWD: ${MAIL_PASS}
      GITEA__APP_NAME: ${APP_NAME}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
    networks:
      - ssl_git
      - gitea
    ports:
      - "2222:22"

  db:
    image: mariadb:10
    container_name: gitea_db
    restart: always
    volumes:
      - gitea_db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: ${SQL_DB}
    networks:
      - gitea
